---
- name: Resource Group Deletion.
  hosts: localhost
  collections:
   - ibm.cloudcollection
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: vars.yml

    - name: Check if resource Group error exists
      ibm_resource_group_info:
        name: "{{ resource_group_name }}"
      failed_when:
         - resource_group_output.rc != 0
         - '"ResourceGroupDoesnotExist" not in resource_group_output.stderr'     
      register: resource_group_output

    - name: Save Resource group info as fact
      set_fact:
        cacheable: True
        resource_group: "{{ resource_group_output.resource }}"
      when: resource_group_output.resource.id is defined

    - name: Delete Resource group
      ibm_resource_group:
        id: "{{ resource_group.id }}"
        state: absent
      register: output
      when: resource_group.id is defined   